
networks:
  app-net:
    driver: bridge

services:
  # ========== INFRASTRUCTURE ==========
  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: telecom-eureka
    networks: [app-net]
    ports: ["8761:8761"]
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION=false
      - EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY=0
      # Use localhost for internal zone to avoid DNS loops during startup
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/
    healthcheck:
      # Use netcat (nc) to just check if the port is open
      test: ["CMD-SHELL", "nc -z localhost 8761 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    networks: [app-net]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx512m"
      KAFKA_JVM_PERFORMANCE_OPTS: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-1.0.1.jar=7071:/opt/jmx-exporter/kafka-jmx-config.yml"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
      - ./jmx_prometheus_javaagent-1.0.1.jar:/opt/jmx-exporter/jmx_prometheus_javaagent-1.0.1.jar
      - ./kafka-jmx-config.yml:/opt/jmx-exporter/kafka-jmx-config.yml
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  kafka-init:
    image: apache/kafka:3.7.0
    container_name: telecom-kafka-init
    networks: [app-net]
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-ec"]
    command:
      - |
        echo "Waiting for Kafka to be fully ready..."
        sleep 5
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic simulation.clock --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic activity.mobility --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic activity.call --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic activity.sms --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic activity.internet --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic activity.total --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic alerts.congestion --partitions 1 --replication-factor 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: telecom-kafka-ui
    ports: ["9021:8080"]
    environment:
      - KAFKA_CLUSTERS_0_NAME=telecom-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on: [kafka]
    networks: [app-net]
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:v1.15
    container_name: telecom-mailpit
    networks:
      - app-net
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    restart: unless-stopped


  # ========== MICROSERVICES ==========
  gateway-service:
    image: ${CI_REGISTRY_IMAGE}/gateway-service:latest
    container_name: telecom-gateway
    depends_on:
      eureka-server:
        condition: service_healthy # Wait for healthcheck to pass
      kafka:
        condition: service_healthy
    entrypoint: ["sh", "-c", "java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx384m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
        - "8090:8090"
    networks: [app-net]
    restart: unless-stopped

  traffic-service:
    image: ${CI_REGISTRY_IMAGE}/traffic-service:latest
    container_name: telecom-traffic-service
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 40 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_STREAMS_PROPERTIES_STATE_DIR: /tmp/kafka-streams
    volumes:
      - traffic-state:/tmp/kafka-streams
    networks: [app-net]
    restart: unless-stopped

  sms-service:
    image: ${CI_REGISTRY_IMAGE}/sms-service:latest
    container_name: telecom-sms-service
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 40 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx384m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks: [app-net]
    restart: unless-stopped

  call-service:
    image: ${CI_REGISTRY_IMAGE}/call-service:latest
    container_name: telecom-call-service
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 40 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks: [app-net]
    restart: unless-stopped

  internet-service:
    image: ${CI_REGISTRY_IMAGE}/internet-service:latest
    container_name: telecom-internet-service
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 40 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks: [app-net]
    restart: unless-stopped

  mobility-service:
    image: ${CI_REGISTRY_IMAGE}/mobility-service:latest
    container_name: telecom-mobility-service
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 40 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx384m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_STREAMS_PROPERTIES_STATE_DIR: /tmp/kafka-streams
    volumes:
      - mobility-state:/tmp/kafka-streams
    networks: [app-net]
    restart: unless-stopped

  alert-service:
    image: ${CI_REGISTRY_IMAGE}/alert-service:latest
    container_name: telecom-alert-service
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 45 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
    networks: [app-net]
    restart: unless-stopped

  cell-service:
    image: ${CI_REGISTRY_IMAGE}/cell-service:latest
    container_name: telecom-cell-service
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 40 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks: [app-net]
    restart: unless-stopped


  producer:
    image: ${CI_REGISTRY_IMAGE}/producer:latest
    container_name: telecom-producer
    depends_on: [kafka]
    entrypoint: ["sh", "-c", "sleep 45 && java -jar app.jar"]
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:+UseG1GC"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_CONTINUE_ON_ERROR: "true"
      PRODUCER_WATERMARKS_RESET_ON_STARTUP: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_URL: jdbc:postgresql://${DB_HOST}:5432/milan_telecom?sslmode=require
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks: [app-net]
    restart: unless-stopped

  # ========== MONITORING ==========
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: telecom-prometheus
    depends_on:
      eureka-server:
        condition: service_healthy # Wait for Eureka to be FULLY ready
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=3d'
    networks: [app-net]
    restart: unless-stopped

volumes:
  kafka-data:
  traffic-state:
  mobility-state:
  prometheus-data:
