server:
  port: 8080

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:telecom-dashboard}
  
  datasource:
    url: jdbc:postgresql://localhost:5432/milan_telecom
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false
  
  cache:
    type: simple
    cache-names:
      - heatmap
  
  kafka:
    bootstrap-servers: kafka:29092

traffic:
  kafka:
    topic: milan.traffic.raw
    client-bootstrap-servers: ${TRAFFIC_KAFKA_CLIENT_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metrics"
  
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s
    enable:
      jvm: true
      process: true
      system: true
      tomcat: true
      logback: true
      jdbc: true
      hikaricp: true
      cache: true
  
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    metadata-map:
      prometheus.path: /actuator/prometheus
      prometheus.port: ${server.port}
      service_group: "telecom"
